"""
Sliding window Hodge monitoring.

Tracks Hodge + persistence features across a pressure time series using a
sliding window. giotto-tda's SlidingWindow handles the windowing; joblib
parallelises window processing.

Usage
-----
from monitoring.sliding_window import run_hodge_monitor

results_df = run_hodge_monitor(
    pressure_signal=bhp,
    times=t,
    window_size=8000,
    stride=200,
    embed_dim=8,
    tau=42,
)
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from gtda.time_series import SlidingWindow

from utils.embedding import takens_embed
from hodge.pipeline import run_window


def _process_one_window(
    window: np.ndarray,
    t_center: float,
    embed_dim: int,
    tau: int,
    n_eigs: int,
    epsilon_strategy: str,
) -> dict:
    embedding = takens_embed(window, embed_dim, tau)
    features = run_window(
        embedding=embedding,
        pressure_window=window,
        n_eigs=n_eigs,
        epsilon_strategy=epsilon_strategy,
    )
    features["time"] = t_center
    return features


def run_hodge_monitor(
    pressure_signal: np.ndarray,
    times: np.ndarray,
    window_size: int,
    stride: int,
    embed_dim: int,
    tau: int,
    n_eigs: int = 20,
    epsilon_strategy: str = "most_persistent",
    n_jobs: int = -1,
) -> pd.DataFrame:
    """
    Run sliding window Hodge + persistence monitoring.

    Windows are generated by giotto-tda's SlidingWindow. Each window
    is processed in parallel via joblib.

    Parameters
    ----------
    pressure_signal : np.ndarray, shape (n_samples,)
    times : np.ndarray, shape (n_samples,)
    window_size, stride : int
    embed_dim, tau : int  — Takens embedding parameters
    n_eigs : int          — number of L₁ eigenvalues per window
    epsilon_strategy : str — "most_persistent" or "max_beta1"
    n_jobs : int          — joblib parallelism (-1 = all cores)

    Returns
    -------
    pd.DataFrame  — one row per window, columns = time + all features
    """
    # Use giotto-tda's SlidingWindow for consistent windowing
    sw = SlidingWindow(size=window_size, stride=stride)
    windows = sw.fit_transform(pressure_signal.reshape(1, -1))[0]
    # windows shape: (n_windows, window_size)

    n_windows = len(windows)
    half = window_size // 2
    # centre timestamp of each window
    indices = [min(i * stride + half, len(times) - 1) for i in range(n_windows)]
    t_centres = [float(times[idx]) for idx in indices]

    results = Parallel(n_jobs=n_jobs, verbose=1)(
        delayed(_process_one_window)(
            window=windows[i],
            t_center=t_centres[i],
            embed_dim=embed_dim,
            tau=tau,
            n_eigs=n_eigs,
            epsilon_strategy=epsilon_strategy,
        )
        for i in range(n_windows)
    )

    return pd.DataFrame(results).sort_values("time").reset_index(drop=True)
